"""Add RecurringShift model

Revision ID: 35391f878e01
Revises: 6826768e20a9
Create Date: 2025-06-19 23:48:14.182962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35391f878e01'
down_revision = '6826768e20a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurring_shift')
    # ### end Alembic commands ###
